##############################################################################
# Copyright (c) 2019 opnfv.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

defaults:
  flavor: m1.tiny # adapt to your environment

testcases:
  sdnvpn.test.functest.testcase_1:
      enabled: true
      description: VPN provides connectivity between subnets
      testname_db: functest_testcase_1
      instance_1_name: sdnvpn-1-1
      instance_2_name: sdnvpn-1-2
      instance_3_name: sdnvpn-1-3
      instance_4_name: sdnvpn-1-4
      instance_5_name: sdnvpn-1-5
      image_name: sdnvpn-image
      net_1_name: sdnvpn-1-1-net
      subnet_1_name: sdnvpn-1-1-subnet
      subnet_1_cidr: 10.10.10.0/24
      router_1_name: sdnvpn-1-1-router
      net_2_name: sdnvpn-1-2-net
      subnet_2_name: sdnvpn-1-2-subnet
      subnet_2_cidr: 10.10.11.0/24
      router_2_name: sdnvpn-1-2-router
      secgroup_name: sdnvpn-sg
      secgroup_descr: Security group for SDNVPN test cases
      targets1: '88:88'
      targets2: '55:55'
      route_distinguishers: '11:11'
