##############################################################################
# Copyright (c) 2019 opnfv.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

defaults:
  flavor: m1.tiny # adapt to your environment

testcases:
  sdnvpn.test.functest.testcase_2:
      enabled: true
      description: Tenant separation
      testname_db: functest_testcase_2
      instance_1_name: sdnvpn-2-1
      instance_2_name: sdnvpn-2-2
      instance_3_name: sdnvpn-2-3
      instance_4_name: sdnvpn-2-4
      instance_5_name: sdnvpn-2-5
      instance_1_ip: 10.10.10.11
      instance_2_ip: 10.10.10.12
      instance_3_ip: 10.10.11.13
      instance_4_ip: 10.10.10.12
      instance_5_ip: 10.10.11.13
      image_name: sdnvpn-image
      net_1_name: sdnvpn-2-1-net
      subnet_1a_name: sdnvpn-2-1a-subnet
      subnet_1a_cidr: 10.10.10.0/24
      subnet_1b_name: sdnvpn-2-1b-subnet
      subnet_1b_cidr: 10.10.11.0/24
      router_1_name: sdnvpn-2-1-router
      net_2_name: sdnvpn-2-2-net
      subnet_2a_name: sdnvpn-2-2a-subnet
      subnet_2a_cidr: 10.10.11.0/24
      subnet_2b_name: sdnvpn-2-2b-subnet
      subnet_2b_cidr: 10.10.10.0/24
      router_2_name: sdnvpn-2-2-router
      secgroup_name: sdnvpn-sg
      secgroup_descr: Security group for SDNVPN test cases
      targets1: '88:88'
      targets2: '55:55'
      route_distinguishers1: '111:111'
      route_distinguishers2: '222:222'
