---
cli:
  arguments:
    config:
      # This is a simple example of arguments.
      # Dovetail has no need of this kind of parameters currently.
      # The arguments must be given orderly at the run-time.
      #
      # docker_tag:
      #   flags: 'docker_tag'
      #   path:
      #     - 'functest/docker_tag'
      #     - 'yardstick/docker_tag'
    control:

  options:
    config:
      yard_tag:
        flags:
          - '--yard_tag'
          - '-y'
        path:
          - 'yardstick/docker_tag'
        help: 'Overwrite tag for yardstick docker container (e.g. stable or latest)'
      func_tag:
        flags:
          - '--func_tag'
          - '-f'
        path:
          - 'functest/docker_tag'
        help: 'Overwrite tag for functest docker container (e.g. stable or latest)'
      openrc:
        flags:
          - '--openrc'
          - '-o'
        path:
          - 'openrc'
        help: 'Openstack Credential file location'
    control:
      testsuite:
        flags:
          - '--testsuite'
        default: 'compliance_set'
        help: 'compliance testsuite.'
      testarea:
        flags:
          - '--testarea'
        default: 'full'
        help: 'compliance testarea within testsuite'
      debug:
        flags:
          - '--debug'
          - '-d'
        is_flag: 'True'
        help: 'Flag for showing debug log on screen.'
      report:
        flags:
          - '--report'
          - '-r'
        help: 'push results to DB (e.g. --report http://192.168.135.2:8000/api/v1)'
      offline:
        flags:
          - '--offline'
        is_flag: 'True'
        help: 'run in offline method'
