---
cli:
  arguments:
    config:
      # This is a simple example of arguments.
      # Dovetail has no need of this kind of parameters currently.
      # The arguments must be given orderly at the run-time.
      #
      # docker_tag:
      #   flags: 'docker_tag'
      #   path:
      #     - 'functest/docker_tag'
      #     - 'yardstick/docker_tag'
    control:

  options:
    config:
      yard_tag:
        flags:
          - '--yard_tag'
          - '-y'
        path:
          - 'yardstick/docker_tag'
        help: 'Overwrite tag for yardstick docker container (e.g. danube.3.2)'
      func_tag:
        flags:
          - '--func_tag'
          - '-f'
        path:
          - 'functest/docker_tag'
        help: 'Overwrite tag for functest docker container (e.g. ovp.1.0.0)'
      # bott_tag:
      #   flags:
      #     - '--bott_tag'
      #     - '-b'
      #   path:
      #     - 'bottlenecks/docker_tag'
      #   help: 'Overwrite tag for bottlenecks docker container (e.g. cvp.0.4.0)'
    control:
      testsuite:
        flags:
          - '--testsuite'
        default: 'ovp.1.0.0'
        help: 'compliance testsuite.'
      testarea:
        flags:
          - '--testarea'
        multiple: 'True'
        help: 'compliance testarea within testsuite'
      debug:
        flags:
          - '--debug'
          - '-d'
        is_flag: 'True'
        help: 'Flag for showing debug log on screen.'
      stop:
        flags:
          - '--stop'
          - '-s'
        is_flag: 'True'
        help: 'Flag for stopping on test case failure.'
      report:
        flags:
          - '--report'
          - '-r'
        help: 'push results to DB (e.g. --report http://192.168.135.2:8000/api/v1/results)'
      offline:
        flags:
          - '--offline'
        is_flag: 'True'
        help: 'run in offline method, which means not to update the docker upstream images, functest, yardstick, etc.'
