---
yardstick:
  image_name: opnfv/yardstick
  docker_tag: latest
  opts: '-id --privileged=true'
  pre_condition:
    - 'source /home/opnfv/repos/yardstick/tests/ci/prepare_env.sh &&
         source /home/opnfv/repos/yardstick/tests/ci/clean_images.sh && cleanup'
    - 'source /home/opnfv/repos/yardstick/tests/ci/prepare_env.sh &&
         cd /home/opnfv/repos/yardstick && source tests/ci/load_images.sh'
  cmds:
    - 'mkdir -p /home/opnfv/yardstick/results/'
    - 'cd /home/opnfv/repos/yardstick && source tests/ci/prepare_env.sh &&
         yardstick task start tests/opnfv/test_cases/{{validate_testcase}}.yaml
         --output-file /home/opnfv/yardstick/results/{{validate_testcase}}.out &>
         /home/opnfv/yardstick/results/yardstick.log'
  post_condition:
    - ''
  result:
    dir: '/home/opnfv/yardstick/results'
    store_type: 'file'
    file_path: 'yardstick.log'
    db_url: 'http://testresults.opnfv.org/test/api/v1/results?case=%s&last=1'
  creds: '/home/opnfv/openrc'
