---
yardstick:
  image_name: opnfv/yardstick
  docker_tag: latest
  opts: '-id --privileged=true'
  pre_condition:
    - 'cd /home/opnfv/repos/yardstick && source tests/ci/prepare_env.sh &&
         source tests/ci/clean_images.sh && cleanup'
    - 'cd /home/opnfv/repos/yardstick && source tests/ci/prepare_env.sh &&
         source tests/ci/load_images.sh'
  cmds:
    - 'mkdir -p /home/opnfv/yardstick/results/'
    - 'cd /home/opnfv/repos/yardstick && source tests/ci/prepare_env.sh &&
         yardstick -d task start tests/opnfv/test_cases/{{validate_testcase}}.yaml
         --output-file /home/opnfv/yardstick/results/{{validate_testcase}}.out'
  post_condition:
    - ''
  result:
    dir: '/home/opnfv/yardstick/results'
    log: '/tmp/yardstick'
    store_type: 'file'
    file_path: 'yardstick.log'
  openrc: '/etc/yardstick/openstack.creds'
