---
docker_images:
  dovetail:
    domain: opnfv
    tag: cvp.0.1.0
    store_name: image_dovetail.docker
  functest:
    domain: opnfv
    tag: danube.2.0
    store_name: image_functest.docker
  yardstick:
    domain: opnfv
    tag: danube.2.0
    store_name: image_yardstick.docker
  testapi:
    domain: opnfv
    tag: cvp.0.1.0
    store_name: image_testapi.docker
  mongo:
    tag: 3.2.1
    store_name: image_mongo.docker
docker_save_path: /home/opnfv/dovetail/results/

wgets:
    sdnvpn:
      source_url: http://artifacts.opnfv.org/sdnvpn/ubuntu-16.04-server-cloudimg-amd64-disk1.img
      save_path: /home/opnfv/dovetail/results/
      file_name: ubuntu-16.04-server-cloudimg-amd64-disk1.img
