---
cli:
  arguments:
    config:
      # This is a simple example of arguments.
      # Dovetail has no need of this kind of parameters currently.
      # The arguments must be given orderly at the run-time.
      #
      # docker_tag:
      #   flags: 'docker_tag'
      #   path:
      #     - 'functest/docker_tag'
      #     - 'yardstick/docker_tag'
    control:

  options:
    config:
    control:
      testsuite:
        flags:
          - '--testsuite'
        default: 'ovp.2018.09'
        help: 'compliance testsuite.'
      testarea:
        flags:
          - '--testarea'
        multiple: 'True'
        help: 'Compliance testarea within testsuite. Specify option multiple times to include multiple test areas.'
      testcase:
        flags:
          - '--testcase'
        multiple: 'True'
        help: 'Compliance testcase. Specify option multiple times to include multiple test cases.'
      debug:
        flags:
          - '--debug'
          - '-d'
        is_flag: 'True'
        help: 'Flag for showing debug log on screen.'
      stop:
        flags:
          - '--stop'
          - '-s'
        is_flag: 'True'
        help: 'Flag for stopping on test case failure.'
      report:
        flags:
          - '--report'
          - '-r'
        is_flag: 'True'
        help: 'Create a tarball file to upload to OVP web portal'
      offline:
        flags:
          - '--offline'
        is_flag: 'True'
        help: 'run in offline method, which means not to update the docker upstream images, functest, yardstick, etc.'
      noapivalidation:
        flags:
          - '--no-api-validation'
        is_flag: 'True'
        help: 'disable strict API response validation'
      noclean:
        flags:
          - '--no-clean'
          - '-n'
        is_flag: 'True'
        help: 'Keep all Containers created for debuging.'
      deployscenario:
        flags:
          - '--deploy-scenario'
        help: 'Specify the DEPLOY_SCENARIO which will be used as input by each testcase respectively'
      mandatory:
        flags:
          - '--mandatory'
        is_flag: 'True'
        help: 'Run all mandatory test cases.'
      optional:
        flags:
          - '--optional'
        is_flag: 'True'
        help: 'Run all optional test cases.'
