---
cli_file_name: 'cmd_config.yml'
result_file: 'results.json'

# OPENSTACK Credential file
env_file: 'env_config.sh'

# POD info file
pod_file: 'pod.yaml'

# JUMPSERVER private key used in pod_file to login hosts
# If use password to login hosts, there's no need to provide the private key
pri_key: 'id_rsa'

# testsuite supported, should adjust accordingly
testsuite_supported:
  - proposed_tests
  - debug
  - healthcheck
  - ovp.next
  - onap.1.0.0
# testarea supported, should adjust accordingly
testarea_supported:
  - ha
  - healthcheck
  - onap
  - sdnvpn
  - security
  - snaps
  - stress
  - tempest
  - vnf
  - vping

# used for testcase cmd template in jinja2 format
# we have two variables available now
# parameter path, use this path to walk through python object and get value
# and the python object is "testcase" object by hard-coded
parameters:
  - name: testcase
    path: '("name",)'
  - name: validate_testcase
    path: '("validate", "testcase")'

include_config:
  - vnftest_config.yml
