---
vnftest:
  image_name: onap/vnfsdk/vnftest
  docker_tag: latest
  opts: '-id --privileged=true'
  config:
    dir: '/home/onap/userconfig'
  pre_condition:
    - 'echo this is pre_condition'
  cmds:
    - 'mkdir -p /home/onap/vnftest/results/'
    - "cd /home/onap/repos/vnftest && source /etc/vnftest/openstack.creds &&
         export CONF_FILE=/etc/vnftest/vnftest.yaml &&
         vnftest task start --output-file /home/onap/vnftest/results/{{testcase}}.out
         /etc/vnftest/vnf_descriptor.yaml
         tests/onap/test_cases/{{validate_testcase}}.yaml"
  post_condition:
    - 'echo this is post_condition'
  result:
    dir: '/home/onap/vnftest/results'
    log: '/tmp/vnftest'
    key_path: '/root/.ssh/id_rsa'
  openrc: '/etc/vnftest/openstack.creds'
  vnftest_conf:
  -
    src_file: '/home/opnfv/dovetail/pre_config/vnftest_conf.yaml'
    dest_file: '/etc/vnftest/vnftest.yaml'
  -
    src_file: '/home/opnfv/dovetail/pre_config/vnf_descriptor.yaml'
    dest_file: '/etc/vnftest/vnf_descriptor.yaml'
